set_property SRC_FILE_INFO {cfile:/home/jeremiah/Programming/FPGA/Vivado/MicroPhaseZ7_Lite_ScreenHat/MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_clk_wiz_0_0/minimal_clk_wiz_0_0.xdc rfile:../../../MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_clk_wiz_0_0/minimal_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:minimal_i/sregs/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jeremiah/Programming/FPGA/Vivado/MicroPhaseZ7_Lite_ScreenHat/MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_ila_0_0/ila_v6_2/constraints/ila.xdc rfile:../../../MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_ila_0_0/ila_v6_2/constraints/ila.xdc id:2 order:EARLY scoped_inst:minimal_i/displays/ila_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jeremiah/Programming/FPGA/Vivado/MicroPhaseZ7_Lite_ScreenHat/MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_processing_system7_0_0/minimal_processing_system7_0_0.xdc rfile:../../../MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_processing_system7_0_0/minimal_processing_system7_0_0.xdc id:3 order:EARLY scoped_inst:minimal_i/ps/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jeremiah/Programming/FPGA/Vivado/MicroPhaseZ7_Lite_ScreenHat/MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_axi_ethernetlite_0_0/minimal_axi_ethernetlite_0_0.xdc rfile:../../../MicroPhaseZ7_Lite_ScreenHat.gen/sources_1/bd/minimal/ip/minimal_axi_ethernetlite_0_0/minimal_axi_ethernetlite_0_0.xdc id:4 order:EARLY scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jeremiah/Programming/FPGA/Vivado/MicroPhaseZ7_Lite_ScreenHat/MicroPhaseZ7_Lite_ScreenHat.srcs/constrs_1/new/ios.xdc rfile:../../../MicroPhaseZ7_Lite_ScreenHat.srcs/constrs_1/new/ios.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:12 order:LATE scoped_inst:minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:13 order:LATE scoped_inst:minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:14 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:15 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:16 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:17 order:LATE scoped_inst:minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
current_instance minimal_i/sregs/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.100
current_instance
current_instance minimal_i/displays/ila_0/inst
set_property src_info {type:SCOPED_XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -type CDC -id {CDC-10} -user ila -tags "1191969" -description "CDC-10 waiver for DDR Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*CLK} -of_objects [get_cells -hierarchical -filter {NAME =~*u_trig/N_DDR_TC.N_DDR_TC_INST[*].U_TC/allx_typeA_match_detection.ltlib_v1_0_3_allx_typeA_inst/DUT/u_srl_drive}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*u_trig/N_DDR_TC.N_DDR_TC_INST[*].U_TC/allx_typeA_match_detection.ltlib_v1_0_3_allx_typeA_inst/DUT/I_IS_TERMINATION_SLICE_W_OUTPUT_REG.DOUT_O_reg}]]
current_instance
current_instance minimal_i/ps/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.49998
set_property src_info {type:SCOPED_XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B15" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E12" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C17" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A5" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B8" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P4" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W5" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W4" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C1" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:3 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:3 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:3 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y2" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:3 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y4" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:3 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:3 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:3 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V1" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:3 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U3" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:3 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:3 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U4" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:3 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T4" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:3 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:3 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:3 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:3 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:3 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:3 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G3" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N1" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:3 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:3 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:3 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L5" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J4" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M3" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K2" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F5" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:3 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:3 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0
set_property src_info {type:SCOPED_XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-10} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */TX/axi_phy_tx_en_i_p_reg*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-12} -user "axi_ethernetlite" -desc "Waiving the CDC-12 As all the reported failures are in Loopback mode where tx_clk and rx_clk are same but tool is treating them as different clocks" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */TX/axi_phy_tx_en_i_p_reg*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-10} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */INST_TX_STATE_MACHINE/STATE*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-13} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */loopback_en_reg*}] -filter {name =~ *C}] -to [list [get_pins -of [get_cells -hier -filter {name =~ */LOOPBACK_GEN.*.CLOCK_MUX*}] -filter {name =~ *CE*}] [get_pins -of [get_cells -hier -filter {name =~ */gen_wr_a.gen_word_narrow.mem_reg_0_15_0_5/RAMA*}] -filter {name =~ *I}]]
set_property src_info {type:SCOPED_XDC file:4 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-10} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */loopback_en_reg*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-12} -user "axi_ethernetlite" -desc "Waiving the CDC-12 As all the reported failures are in Loopback mode where tx_clk and rx_clk are same but tool is treating them as diffrent clocks" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */loopback_en_reg*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-10} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */TX/INST_TX_STATE_MACHINE/phytx_en_reg_reg*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-10} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */TX/tx3_generate.INST_JAMTXNIBCNT/PERBIT_GEN[*].FF_RST*_GEN.*_i1*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
set_property src_info {type:SCOPED_XDC file:4 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-10} -user "axi_ethernetlite" -desc "This is sustaining IP so there is no core level change hence waived" -tags "11999" -from [get_pins -of [get_cells -hier -filter {name =~ */TX/INST_TX_STATE_MACHINE/PRE_SFD_count/zero_i_reg*}] -filter {name =~ *C}] -to [get_pins -of [get_cells -hier -filter {name =~ *CDC_*/syncstages_ff_reg*}] -filter {name =~ *D}]
current_instance
set_property src_info {type:XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_logic_zero [get_ports ETH_MII_col]
set_property src_info {type:XDC file:5 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_logic_zero [get_ports ETH_MII_crs]
set_property src_info {type:XDC file:5 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_logic_zero [get_ports ETH_MII_rx_er]
set_property src_info {type:XDC file:5 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_rxd[3]}]
set_property src_info {type:XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_rxd[2]}]
set_property src_info {type:XDC file:5 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_rxd[1]}]
set_property src_info {type:XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_rxd[0]}]
set_property src_info {type:XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports ETH_MII_rx_clk]
set_property src_info {type:XDC file:5 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports ETH_MII_rx_dv]
set_property src_info {type:XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_txd[3]}]
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_txd[2]}]
set_property src_info {type:XDC file:5 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_txd[1]}]
set_property src_info {type:XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {ETH_MII_txd[0]}]
set_property src_info {type:XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports ETH_MII_tx_clk]
set_property src_info {type:XDC file:5 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports ETH_MII_tx_en]
set_property src_info {type:XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports ETH_MII_rst_n]
set_property src_info {type:XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports ETH_MDIO_mdio_io]
set_property src_info {type:XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports ETH_MDIO_mdc]
set_property src_info {type:XDC file:5 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_0_sda]
set_property src_info {type:XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_1_sda]
set_property src_info {type:XDC file:5 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_2_sda]
set_property src_info {type:XDC file:5 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_3_sda]
set_property src_info {type:XDC file:5 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_4_sda]
set_property src_info {type:XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_5_sda]
set_property src_info {type:XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_6_sda]
set_property src_info {type:XDC file:5 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_7_sda]
set_property src_info {type:XDC file:5 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_8_sda]
set_property src_info {type:XDC file:5 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_9_sda]
set_property src_info {type:XDC file:5 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_A_sda]
set_property src_info {type:XDC file:5 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_B_sda]
set_property src_info {type:XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_C_sda]
set_property src_info {type:XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_D_sda]
set_property src_info {type:XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_0_scl]
set_property src_info {type:XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_1_scl]
set_property src_info {type:XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_2_scl]
set_property src_info {type:XDC file:5 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_3_scl]
set_property src_info {type:XDC file:5 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_4_scl]
set_property src_info {type:XDC file:5 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_5_scl]
set_property src_info {type:XDC file:5 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_6_scl]
set_property src_info {type:XDC file:5 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_7_scl]
set_property src_info {type:XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_8_scl]
set_property src_info {type:XDC file:5 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_9_scl]
set_property src_info {type:XDC file:5 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_A_scl]
set_property src_info {type:XDC file:5 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_B_scl]
set_property src_info {type:XDC file:5 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_C_scl]
set_property src_info {type:XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports ILI_D_scl]
set_property src_info {type:XDC file:5 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports ILI_0_cs]
set_property src_info {type:XDC file:5 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports ILI_1_cs]
set_property src_info {type:XDC file:5 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports ILI_2_cs]
set_property src_info {type:XDC file:5 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports ILI_3_cs]
set_property src_info {type:XDC file:5 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports ILI_4_cs]
set_property src_info {type:XDC file:5 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports ILI_5_cs]
set_property src_info {type:XDC file:5 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports ILI_6_cs]
set_property src_info {type:XDC file:5 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports ILI_7_cs]
set_property src_info {type:XDC file:5 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports ILI_8_cs]
set_property src_info {type:XDC file:5 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports ILI_9_cs]
set_property src_info {type:XDC file:5 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports ILI_A_cs]
set_property src_info {type:XDC file:5 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports ILI_B_cs]
set_property src_info {type:XDC file:5 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports ILI_C_cs]
set_property src_info {type:XDC file:5 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports ILI_D_cs]
set_property src_info {type:XDC file:5 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports ILI_0_dc]
set_property src_info {type:XDC file:5 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports ILI_1_dc]
set_property src_info {type:XDC file:5 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports ILI_2_dc]
set_property src_info {type:XDC file:5 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports ILI_3_dc]
set_property src_info {type:XDC file:5 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports ILI_4_dc]
set_property src_info {type:XDC file:5 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports ILI_5_dc]
set_property src_info {type:XDC file:5 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports ILI_6_dc]
set_property src_info {type:XDC file:5 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports ILI_7_dc]
set_property src_info {type:XDC file:5 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports ILI_8_dc]
set_property src_info {type:XDC file:5 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports ILI_9_dc]
set_property src_info {type:XDC file:5 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports ILI_A_dc]
set_property src_info {type:XDC file:5 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports ILI_B_dc]
set_property src_info {type:XDC file:5 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports ILI_C_dc]
set_property src_info {type:XDC file:5 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports ILI_D_dc]
set_property src_info {type:XDC file:5 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports rst595_resetn]
set_property src_info {type:XDC file:5 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports rst595_latch]
set_property src_info {type:XDC file:5 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports rst595_clock]
set_property src_info {type:XDC file:5 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports rst595_data]
set_property src_info {type:XDC file:5 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports led595_resetn]
set_property src_info {type:XDC file:5 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports led595_latch]
set_property src_info {type:XDC file:5 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports led595_clock]
set_property src_info {type:XDC file:5 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33 DRIVE 8 SLEW FAST} [get_ports led595_data]
set_property src_info {type:XDC file:5 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name RST_SREG_CLK -source [get_clocks clk_out1_minimal_clk_wiz_0_0] -divide_by 1 [get_ports rst595_clock]
set_property src_info {type:XDC file:5 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock RST_SREG_CLK -min -10  [get_ports rst595_data]
set_property src_info {type:XDC file:5 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock RST_SREG_CLK -min -10  [get_ports rst595_latch]
set_property src_info {type:XDC file:5 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock RST_SREG_CLK -min -10  [get_ports rst595_resetn]
set_property src_info {type:XDC file:5 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock RST_SREG_CLK -max 10   [get_ports rst595_data]
set_property src_info {type:XDC file:5 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock RST_SREG_CLK -max 10   [get_ports rst595_latch]
set_property src_info {type:XDC file:5 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock RST_SREG_CLK -max 10   [get_ports rst595_resetn]
set_property src_info {type:XDC file:5 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name LED_SREG_CLK -source [get_clocks clk_out1_minimal_clk_wiz_0_0] -divide_by 1 [get_ports led595_clock]
set_property src_info {type:XDC file:5 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock LED_SREG_CLK -min -10  [get_ports led595_data]
set_property src_info {type:XDC file:5 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock LED_SREG_CLK -min -10  [get_ports led595_latch]
set_property src_info {type:XDC file:5 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock LED_SREG_CLK -min -10  [get_ports led595_resetn]
set_property src_info {type:XDC file:5 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock LED_SREG_CLK -max 10   [get_ports led595_data]
set_property src_info {type:XDC file:5 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock LED_SREG_CLK -max 10   [get_ports led595_latch]
set_property src_info {type:XDC file:5 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock LED_SREG_CLK -max 10   [get_ports led595_resetn]
set_property src_info {type:XDC file:5 line:156 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_0_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_0_scl]
set_property src_info {type:XDC file:5 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_0_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_0_sda]
set_property src_info {type:XDC file:5 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_0_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_0_sda]
set_property src_info {type:XDC file:5 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_0_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_0_cs]
set_property src_info {type:XDC file:5 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_0_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_0_cs]
set_property src_info {type:XDC file:5 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_0_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_0_dc]
set_property src_info {type:XDC file:5 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_0_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_0_dc]
set_property src_info {type:XDC file:5 line:164 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_1_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_1_scl]
set_property src_info {type:XDC file:5 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_1_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_1_sda]
set_property src_info {type:XDC file:5 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_1_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_1_sda]
set_property src_info {type:XDC file:5 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_1_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_1_cs]
set_property src_info {type:XDC file:5 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_1_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_1_cs]
set_property src_info {type:XDC file:5 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_1_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_1_dc]
set_property src_info {type:XDC file:5 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_1_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_1_dc]
set_property src_info {type:XDC file:5 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_2_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_2_scl]
set_property src_info {type:XDC file:5 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_2_CLK -max [expr {10.0 + 3.0}]       [get_ports ILI_2_sda]
set_property src_info {type:XDC file:5 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_2_CLK -min [expr {-1 * (10.0 + 3.0)}] [get_ports ILI_2_sda]
set_property src_info {type:XDC file:5 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_2_CLK -max [expr {10.0 + 3.0}]       [get_ports ILI_2_cs]
set_property src_info {type:XDC file:5 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_2_CLK -min [expr {-1 * (10.0 + 3.0)}] [get_ports ILI_2_cs]
set_property src_info {type:XDC file:5 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_2_CLK -max [expr {10.0 + 3.0}]       [get_ports ILI_2_dc]
set_property src_info {type:XDC file:5 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_2_CLK -min [expr {-1 * (10.0 + 3.0)}] [get_ports ILI_2_dc]
set_property src_info {type:XDC file:5 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_3_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_3_scl]
set_property src_info {type:XDC file:5 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_3_CLK -max [expr {10.0 + 4.0}]       [get_ports ILI_3_sda]
set_property src_info {type:XDC file:5 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_3_CLK -min [expr {-1 * (10.0 + 4.0)}] [get_ports ILI_3_sda]
set_property src_info {type:XDC file:5 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_3_CLK -max [expr {10.0 + 4.0}]       [get_ports ILI_3_cs]
set_property src_info {type:XDC file:5 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_3_CLK -min [expr {-1 * (10.0 + 4.0)}] [get_ports ILI_3_cs]
set_property src_info {type:XDC file:5 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_3_CLK -max [expr {10.0 + 4.0}]       [get_ports ILI_3_dc]
set_property src_info {type:XDC file:5 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_3_CLK -min [expr {-1 * (10.0 + 4.0)}] [get_ports ILI_3_dc]
set_property src_info {type:XDC file:5 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_4_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_4_scl]
set_property src_info {type:XDC file:5 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_4_CLK -max [expr {10.0 + 5.0}]       [get_ports ILI_4_sda]
set_property src_info {type:XDC file:5 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_4_CLK -min [expr {-1 * (10.0 + 5.0)}] [get_ports ILI_4_sda]
set_property src_info {type:XDC file:5 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_4_CLK -max [expr {10.0 + 5.0}]       [get_ports ILI_4_cs]
set_property src_info {type:XDC file:5 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_4_CLK -min [expr {-1 * (10.0 + 5.0)}] [get_ports ILI_4_cs]
set_property src_info {type:XDC file:5 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_4_CLK -max [expr {10.0 + 5.0}]       [get_ports ILI_4_dc]
set_property src_info {type:XDC file:5 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_4_CLK -min [expr {-1 * (10.0 + 5.0)}] [get_ports ILI_4_dc]
set_property src_info {type:XDC file:5 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_5_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_5_scl]
set_property src_info {type:XDC file:5 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_5_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_5_sda]
set_property src_info {type:XDC file:5 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_5_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_5_sda]
set_property src_info {type:XDC file:5 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_5_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_5_cs]
set_property src_info {type:XDC file:5 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_5_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_5_cs]
set_property src_info {type:XDC file:5 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_5_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_5_dc]
set_property src_info {type:XDC file:5 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_5_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_5_dc]
set_property src_info {type:XDC file:5 line:204 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_6_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_6_scl]
set_property src_info {type:XDC file:5 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_6_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_6_sda]
set_property src_info {type:XDC file:5 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_6_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_6_sda]
set_property src_info {type:XDC file:5 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_6_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_6_cs]
set_property src_info {type:XDC file:5 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_6_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_6_cs]
set_property src_info {type:XDC file:5 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_6_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_6_dc]
set_property src_info {type:XDC file:5 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_6_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_6_dc]
set_property src_info {type:XDC file:5 line:212 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_7_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_7_scl]
set_property src_info {type:XDC file:5 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_7_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_7_sda]
set_property src_info {type:XDC file:5 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_7_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_7_sda]
set_property src_info {type:XDC file:5 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_7_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_7_cs]
set_property src_info {type:XDC file:5 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_7_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_7_cs]
set_property src_info {type:XDC file:5 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_7_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_7_dc]
set_property src_info {type:XDC file:5 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_7_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_7_dc]
set_property src_info {type:XDC file:5 line:220 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_8_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_8_scl]
set_property src_info {type:XDC file:5 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_8_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_8_sda]
set_property src_info {type:XDC file:5 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_8_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_8_sda]
set_property src_info {type:XDC file:5 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_8_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_8_cs]
set_property src_info {type:XDC file:5 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_8_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_8_cs]
set_property src_info {type:XDC file:5 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_8_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_8_dc]
set_property src_info {type:XDC file:5 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_8_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_8_dc]
set_property src_info {type:XDC file:5 line:228 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_9_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_9_scl]
set_property src_info {type:XDC file:5 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_9_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_9_sda]
set_property src_info {type:XDC file:5 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_9_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_9_sda]
set_property src_info {type:XDC file:5 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_9_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_9_cs]
set_property src_info {type:XDC file:5 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_9_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_9_cs]
set_property src_info {type:XDC file:5 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_9_CLK -max [expr {10.0 + 6.0}]       [get_ports ILI_9_dc]
set_property src_info {type:XDC file:5 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_9_CLK -min [expr {-1 * (10.0 + 6.0)}] [get_ports ILI_9_dc]
set_property src_info {type:XDC file:5 line:236 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_A_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_A_scl]
set_property src_info {type:XDC file:5 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_A_CLK -max [expr {10.0 + 5.0}]       [get_ports ILI_A_sda]
set_property src_info {type:XDC file:5 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_A_CLK -min [expr {-1 * (10.0 + 5.0)}] [get_ports ILI_A_sda]
set_property src_info {type:XDC file:5 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_A_CLK -max [expr {10.0 + 5.0}]       [get_ports ILI_A_cs]
set_property src_info {type:XDC file:5 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_A_CLK -min [expr {-1 * (10.0 + 5.0)}] [get_ports ILI_A_cs]
set_property src_info {type:XDC file:5 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_A_CLK -max [expr {10.0 + 5.0}]       [get_ports ILI_A_dc]
set_property src_info {type:XDC file:5 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_A_CLK -min [expr {-1 * (10.0 + 5.0)}] [get_ports ILI_A_dc]
set_property src_info {type:XDC file:5 line:244 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_B_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_B_scl]
set_property src_info {type:XDC file:5 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_B_CLK -max [expr {10.0 + 4.0}]       [get_ports ILI_B_sda]
set_property src_info {type:XDC file:5 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_B_CLK -min [expr {-1 * (10.0 + 4.0)}] [get_ports ILI_B_sda]
set_property src_info {type:XDC file:5 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_B_CLK -max [expr {10.0 + 4.0}]       [get_ports ILI_B_cs]
set_property src_info {type:XDC file:5 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_B_CLK -min [expr {-1 * (10.0 + 4.0)}] [get_ports ILI_B_cs]
set_property src_info {type:XDC file:5 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_B_CLK -max [expr {10.0 + 4.0}]       [get_ports ILI_B_dc]
set_property src_info {type:XDC file:5 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_B_CLK -min [expr {-1 * (10.0 + 4.0)}] [get_ports ILI_B_dc]
set_property src_info {type:XDC file:5 line:252 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_C_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_C_scl]
set_property src_info {type:XDC file:5 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_C_CLK -max [expr {10.0 + 3.0}]       [get_ports ILI_C_sda]
set_property src_info {type:XDC file:5 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_C_CLK -min [expr {-1 * (10.0 + 3.0)}] [get_ports ILI_C_sda]
set_property src_info {type:XDC file:5 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_C_CLK -max [expr {10.0 + 3.0}]       [get_ports ILI_C_cs]
set_property src_info {type:XDC file:5 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_C_CLK -min [expr {-1 * (10.0 + 3.0)}] [get_ports ILI_C_cs]
set_property src_info {type:XDC file:5 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_C_CLK -max [expr {10.0 + 3.0}]       [get_ports ILI_C_dc]
set_property src_info {type:XDC file:5 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_C_CLK -min [expr {-1 * (10.0 + 3.0)}] [get_ports ILI_C_dc]
set_property src_info {type:XDC file:5 line:260 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ILI_D_CLK -source [get_clocks clk_fpga_1] -divide_by 1    [get_ports ILI_D_scl]
set_property src_info {type:XDC file:5 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_D_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_D_sda]
set_property src_info {type:XDC file:5 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_D_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_D_sda]
set_property src_info {type:XDC file:5 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_D_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_D_cs]
set_property src_info {type:XDC file:5 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_D_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_D_cs]
set_property src_info {type:XDC file:5 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_D_CLK -max [expr {10.0 + 2.0}]       [get_ports ILI_D_dc]
set_property src_info {type:XDC file:5 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock ILI_D_CLK -min [expr {-1 * (10.0 + 2.0)}] [get_ports ILI_D_dc]
set_property src_info {type:XDC file:5 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_fpga_0 -min -0.5 [get_ports ETH_MII_rx_clk]
set_property src_info {type:XDC file:5 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_fpga_0 -max 0.5  [get_ports ETH_MII_rx_clk]
set_property src_info {type:XDC file:5 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_fpga_0 -min -0.5 [get_ports ETH_MII_tx_clk]
set_property src_info {type:XDC file:5 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_fpga_0 -max 0.5  [get_ports ETH_MII_tx_clk]
current_instance minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:9 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:10 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:11 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:12 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/axis_clock_converter_0/inst/gen_async_conv.axisc_async_clock_converter_0/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:13 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:14 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/RX/INST_RX_INTRFCE/I_RX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:15 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:16 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance minimal_i/ps/axi_ethernetlite_0/U0/XEMAC_I/EMAC_I/TX/INST_TX_INTRFCE/I_TX_FIFO/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:17 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
